### ISSUE TITLE
amber-cmd formula doesn't seem to be in Homebrew

### ISSUE THREAD

**Issue by dtakahas** [Amber-Crystal/amber_cmd#10]
The [installation](https://amber-crystal.gitbooks.io/amber/content/getting-started/installation/heroku.html) instructions mention that amber-cmd is available via Homebrew, but it seems to be missing. I'm pretty sure my brew repo is up to date. Anything I'm missing?

**Comment by elorest** [comment]
Yeah for now it's probably best to install from source.
git clone
cd amber-cmd
make

**Comment by eliasjpr** [comment]
PR opened for this https://github.com/Amber-Crystal/amber_cmd/pull/17

**Comment by eliasjpr** [comment]
You can install it by using the following command **brew install https://raw.githubusercontent.com/Amber-Crystal/amber_cmd/ep/brew-formula-amber_cmd/amber_cmd.rb** until we get the formula accepted by the hombres team.

**Comment by eliasjpr** [comment]
We need more stars, forks in order for the homebrew accepts our formula

**Comment by eliasjpr** [comment]
@dtakahas you can now install the cli with
```bash
brew install amber-crystal/amber/amber

# or 

brew tap amber-crystal/amber
brew install amber-crystal/amber
```
