### ISSUE TITLE
Cleanup Generated App PORT and AMBER_ENV

### ISSUE THREAD

**Issue by eliasjpr** [Amber-Crystal/amber_cmd#23]
> As a developer I want to be able to set the PORT and AMBER_ENV via a command line argument

```bash
amber run -p 5000 -e development
```
Acceptance Criteria

- [x] The command should be able to take 2 arguments PORT and ENVIRONMENT
- [x] The command should set the ENV["PORT"] and ENV["AMBER_ENV"] variables
- [x] The command starts the amber server

**Comment by eliasjpr** [comment]
PR https://github.com/Amber-Crystal/amber_cmd/pull/22

**Comment by drujensen** [comment]
This issue has been merged
