### ISSUE TITLE
failed to run `brew install` based on README instructions

### ISSUE THREAD

**Issue by drujensen** [Amber-Crystal/amber_cmd#24]
$brew install amber-crystal/amber
Error: No available formula with the name "amber-crystal/amber" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
This similarly named formula was found:
amber-crystal/amber/amber
To install it, run:
  brew install amber-crystal/amber/amber

**Comment by eliasjpr** [comment]
@drujensen you have to first tap and then install or you can do `brew install amber-crystal/amber/amber`

**Comment by drujensen** [comment]
Here is the full output:
```
drujensen:~
$brew tap amber-crystal/amber
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).

drujensen:~
$brew install amber-crystal/amber
Error: No available formula with the name "amber-crystal/amber" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
This similarly named formula was found:
amber-crystal/amber/amber ✔
To install it, run:
  brew install amber-crystal/amber/amber ✔
drujensen:~
$
```

**Comment by drujensen** [comment]
This issue has been fixed
