### ISSUE TITLE
Generate Mailers Command

### ISSUE THREAD

**Issue by eliasjpr** [Amber-Crystal/amber_cmd#27]
> As a developer I want to be able to send emails from within the application

Acceptance Criteria:
- [x] Be able to run `amber g mailer {NAME}`
- [x] Generate Mailer class
- [x] Generates View for mailer
- [ ] Generates Test for mailer

**Comment by eliasjpr** [comment]
PR https://github.com/Amber-Crystal/amber_cmd/pull/25

**Comment by drujensen** [comment]
This has been merged
