### ISSUE TITLE
Define amber run command 

### ISSUE THREAD

**Issue by eliasjpr** [Amber-Crystal/amber_cmd#3]
> As a Developer, I want to be able to run my project for a specific port and environment with a single command

```bash
amber run # Runs with defaults PORT 3000 AMBER_ENV development 
amber run -p NUMBER -e ENVIRONMENT
```

**Acceptance Criteria:**
- [x] Execute command with default port **300** and env **development**
- [x] Execute command with specific port 
- [x] Execute command with specific env **development**
- [x] Compiles crystal project with `--release` flag for env **production**

**Comment by eliasjpr** [comment]
https://github.com/Amber-Crystal/amber_cmd/pull/22

**Comment by drujensen** [comment]
This has been merged
