### ISSUE TITLE
AMBER_ENV is undefined

### ISSUE THREAD

**Issue by drujensen** [Amber-Crystal/amber_cmd#32]
When trying to `require ./config/*`, the AMBER_ENV is not defined. 

https://github.com/Amber-Crystal/amber_cmd/blob/master/src/templates/app/config/application.cr.ecr#L6

It seems we have a reverse dependency on the `src/blog.cr` to be the only entry point.  This causes issues when needing to load the resources in a different application.

**Comment by eliasjpr** [comment]
We are removing AMBER_ENV constant in this PR https://github.com/Amber-Crystal/amber_cmd/pull/21

**Comment by drujensen** [comment]
this is resolved now that the PR is merged.
