### ISSUE TITLE
Missing version.cr in generated project

### ISSUE THREAD

**Issue by eliasjpr** [Amber-Crystal/amber_cmd#9]
The **src/<name>/version.cr** file is missing when generating a new project.

AC:

- [ ] Generate a new project with a valid version.cr file

**Comment by eliasjpr** [comment]
Is this a valid issue still?

**Comment by elorest** [comment]
No we decided just to use the shard.yml version for web apps.

**Comment by eliasjpr** [comment]
Closing thing issue
